# Site settings
author: Will Lawrence
title: Will's future in coding
header-img: img/home-bg.png
email: will.lawrence.3rd@gmail.com
copyright_name: Will Lawrence
description: > # this means to ignore newlines until "baseurl:"
  Why Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: DanceKwesi
github_username:  Addae07

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
